<DOCTYPE html>
    <html>
    <head>
    </head>
    <title>Regisration Page</title>
        <body>
            <div>
                <h1> REGISRATION FORM </h1>
                <div class="main"></div>
                <form action="connect.php" method="POST" autocomplete="off">
                </form></div>
            <h2 class="name">Username:</h2>
    <input type="text" class="username" name="Username" >
                <h2 class="name"> EMAIL: </h2>
                <input type="text" class="Email" name="Email">
            <h4 class="name">NAME</h4>
            <input type="text" class="NAME" name="NAME">
            <h5 class="name">PHONE NUMBER:</h5>
            <input type="text" class="phone number"name="phone number">
            <h6 class="name">IDNO:</h6>
            <input type="text" class="IDNO" name="IDNO">
            <h7 class="text">PASSWORD:</h7>
            <input type="name"class="password"name="password">
            <p class="condition"> <input type ="checkbox" id="terms" name=""> I accept the terms and conditions</p><br><br>
    <button type="submit" ><b></b>REGISTER</b></button>

            

    
            </form>    
        </body>
    </html>